[project]
name = "mlops-test1"
version = "0.1.0"
description = "primer test con poetry"
authors = [
    {name = "albertovh71",email = "albertovh71@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
